windowrule {
    name = ardour
    match:class = ^(Ardour.*)$
    match:xwayland = on

    #no_focus = on
    no_anim = on
    float = on
    no_initial_focus = on
}

windowrule {
    name = qpwgraph
    match:class = ^(qpwgraph.*)$

    #no_focus = on
    no_anim = on
    float = on
    no_initial_focus = on
}
