# Browser types
windowrule = tag +chromium-based-browser, match:class ((google-)?[cC]hrom(e|ium)|[bB]rave-browser|Microsoft-edge|Vivaldi-stable|helium)
windowrule = tag +chromium-based-browser, match:class ([Gg]oogle-chrome(-beta|-dev|-unstable)?)
windowrule = tag +chromium-based-browser, match:class (chrome-.+-Default)
windowrule = tag +chromium-based-browser, match:class ([Mm]icrosoft-edge(-stable|-beta|-dev|-unstable))
windowrule = tag +chromium-based-browser, match:class (Brave-browser(-beta|-dev|-unstable)?)
windowrule = tag +chromium-based-browser, match:class ([Tt]horium-browser|[Cc]achy-browser)
windowrule = tag +firefox-based-browser, match:class ([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr|[Ff]irefox-bin)
windowrule = tag +firefox-based-browser, match:class (zen-alpha|zen)
# browser tags
windowrule = match:class ^([Ff]irefox|org.mozilla.firefox|[Ff]irefox-esr|[Ff]irefox-bin)$, tag +browser
windowrule = match:class ^([Gg]oogle-chrome(-beta|-dev|-unstable)?)$, tag +browser
windowrule = match:class ^(chrome-.+-Default)$, tag +browser
windowrule = match:class ^([Cc]hromium)$, tag +browser
windowrule = match:class ^([Mm]icrosoft-edge(-stable|-beta|-dev|-unstable))$, tag +browser
windowrule = match:class ^(Brave-browser(-beta|-dev|-unstable)?)$, tag +browser
windowrule = match:class ^([Tt]horium-browser|[Cc]achy-browser)$, tag +browser
windowrule = match:class ^(zen)$, tag +browser


# Video apps: remove chromium browser tag so they don't get opacity applied
windowrule = tag -chromium-based-browser, match:class (chrome-youtube.com__-Default|chrome-app.zoom.us__wc_home-Default)
windowrule = tag -default-opacity, match:class (chrome-youtube.com__-Default|chrome-app.zoom.us__wc_home-Default)

# Force chromium-based browsers into a tile to deal with --app bug
windowrule = tile on, match:tag chromium-based-browser

# Only a subtle opacity change, but not for video sites
#windowrule = opacity 1.0 0.97, match:tag chromium-based-browser
#windowrule = opacity 1.0 0.97, match:tag firefox-based-browser