 windowrule {
    name = godot-game
    match:initial_class = (Godot|org.godotengine.Editor)
    match:initial_title = Godot
    tag = +godot
    
    no_initial_focus = on
}

windowrule {
    name = godot-game
    match:title = .*(DEBUG).*
    match:initial_class = Godot
    tag = +godot

    fullscreen = off
    maximize = on
    float = off
}
windowrule {
    name = godot-game-2
    match:initial_title = .*(DEBUG).*
    match:initial_class = Godot

    fullscreen = off
    maximize = off
    center = on
    float = on
}
windowrule {
    name = godot-game-3
    match:title = .*(DEBUG).*
    match:initial_title = Godot

    fullscreen = off
    maximize = off
    center = on
    float = on
}

windowrule {
    name = godot-dialog
    match:title = ^(Open .*|Editor Settings.*|Select.*|Project Settings.*|Save .*|Please Confirm.*|Create .*|Command Palette|Export|Attach Node .*)$
    match:initial_class = (Godot|org.godotengine.Editor)

    tag = +godot
    center = on
    float = on
    stay_focused = on
    size = (monitor_w*0.5) (monitor_h*0.75)
}