# IM tags
windowrule = match:class ^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$, tag +im
windowrule = match:class ^([Ff]erdium)$, tag +im
windowrule = match:class ^([Ww]hatsapp-for-linux)$, tag +im
windowrule = match:class ^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$, tag +im
windowrule = match:class ^(teams-for-linux)$, tag +im
windowrule = match:class ^(im.riot.Riot|Element)$, tag +im

# windowrule = tag +im, class:^([Dd]iscord|[Ww]ebCord|[Vv]esktop)$
windowrule {
  name = ferdium
  match:class = ^([Ff]erdium)$
  tag = +im

  size = (monitor_w*0.6) (monitor_h*0.7)
  
  center = on
  float = on
}

windowrule {
  name = whatps-app
  tag = +im
  match:class = ^([Ww]hatsapp-for-linux)$
}

windowrule {
  name = zapzap
  tag = +im
  match:class = ^(ZapZap|com.rtosta.zapzap)$
}

windowrule {
  name = telegram
  tag = +im
  match:class = ^(org.telegram.desktop|io.github.tdesktop_x64.TDesktop)$
}

windowrule {
  name = teams
  tag = +im
  match:class = ^(teams-for-linux)$
}

windowrule {
  name = matrix-element
  tag = +im
  match:class = ^(im.riot.Riot|Element)$ # Element Matrix client
}
