# Float Steam
windowrule = float on, match:class steam
windowrule = center on, match:class steam, match:title Steam
windowrule = tag -default-opacity, match:class steam.*
windowrule = opacity 1 1, match:class steam.*
windowrule = size 1100 700, match:class steam, match:title Steam
windowrule = size 460 800, match:class steam, match:title Friends List
windowrule = idle_inhibit fullscreen, match:class steam

windowrule {
  name = games
  match:tag = game
  
  no_blur = on
}
windowrule = match:tag games, no_blur on, fullscreen 0
windowrule = match:tag games, fullscreen 0