#!/usr/bin/env bash
#    ____         __       ____               __     __
#   /  _/__  ___ / /____ _/ / / __ _____  ___/ /__ _/ /____ ___
#  _/ // _ \(_-</ __/ _ `/ / / / // / _ \/ _  / _ `/ __/ -_|_-<
# /___/_//_/___/\__/\_,_/_/_/  \_,_/ .__/\_,_/\_,_/\__/\__/___/
#                                 /_/
#

# show packages NEWER then X days
UPDATE_AGE_DAYS=7

# Check if command exists
_checkCommandExists() {
    cmd="$1"
    if ! command -v "$cmd" >/dev/null; then
        echo 1
        return
    fi
    echo 0
    return
}

_isInstalled() {
    package="$1"
    case $install_platform in
        arch)
            check="$($aur_helper -Qs --color always "${package}" | grep "local" | grep "${package} ")"
            ;;
        fedora)
            check="$(dnf repoquery --quiet --installed ""${package}*"")"
            ;;
        *) ;;
    esac

    if [ -n "${check}" ]; then
        echo 0 #'0' means 'true' in Bash
        return #true
    fi
    echo 1 #'1' means 'false' in Bash
    return #false
}

# ------------------------------------------------------
# Confirm Start
# ------------------------------------------------------

sleep 1
clear
figlet -f smslant "Updates"
echo
primarycolor=$(cat ~/.config/ml4w/colors/primary)
onsurfacecolor=$(cat ~/.config/ml4w/colors/onsurface)
onprimarycolor=$(cat ~/.config/ml4w/colors/onprimary)
if gum confirm --selected.background=$primarycolor --selected.foreground=$onprimarycolor --prompt.foreground=$onsurfacecolor "DO YOU WANT TO START THE UPDATE NOW?"; then
    echo
    echo ":: Update started..."
elif [ $? -eq 130 ]; then
    exit 130
else
    echo
    echo ":: Update canceled."
    exit
fi

# ----------------------------------------------------- 
# Install update
# ----------------------------------------------------- 

# Arch
if [[ $(_checkCommandExists "pacman") == 0 ]]; then
    yay_installed="false"
    paru_installed="false"
    if [[ $(_checkCommandExists "yay") == 0 ]]; then
        yay_installed="true"
    fi
    if [[ $(_checkCommandExists "paru") == 0 ]]; then
        paru_installed="true"
    fi

    show_update_age_cutoff=$(date -d "$UPDATE_AGE_DAYS days ago" +%s)
    echo ":: Checking package update age..."

    warning_found=0
    newest_age=-1
    updates_found=0

    while read -r pkg oldver newver; do
        updates_found=1

        # remove repo prefix for pacman -Qi
        pkg_clean="${pkg#*/}"
        install_date=$(LANG=C pacman -Qi "$pkg_clean" | awk -F': ' '/Installiert am|Install Date/ {print $2}')
        [[ -z "$install_date" ]] && continue

        install_epoch=$(LANG=C date -d "$install_date" +%s 2>/dev/null)
        clean_date=$(echo "$install_date" | sed 's/^[A-Za-zäöüÄÖÜ]* //')
        install_epoch=$(LANG=C date -d "$clean_date" +%s 2>/dev/null)
        [[ -z "$install_epoch" ]] && continue

        diff_days=$(( ( $(date +%s) - install_epoch ) / 86400 ))

        if (( newest_age == -1 || diff_days < newest_age )); then
            newest_age=$diff_days
        fi

        if (( diff_days <= UPDATE_AGE_DAYS )); then
            echo "⚠️ WARNING: $pkg_clean is NEW ($diff_days days old)"
            warning_found=1
        fi

    done < <(pacman -Qu)

    echo

    
    if [[ $updates_found -eq 0 ]]; then
        echo ":: No updates available"
    elif [[ $warning_found -eq 0 ]]; then
        echo -e ":: All updates are stable"
        echo -e ":: Newest update age: $newest_age days"
    else
        echo "⚠️ Some very recent updates were found."
    fi

    if [[ $(_checkCommandExists "cachyos-hello") == 0 ]]; then
        echo ":: Running CachyOS system updater..."
        cachyos-hello fix update-system
    elif [[ $yay_installed == "true" ]] && [[ $paru_installed == "false" ]]; then
        yay
    elif [[ $yay_installed == "false" ]] && [[ $paru_installed == "true" ]]; then
        paru -Syu --noconfirm
    else
        yay
    fi
# Fedora
elif [[ $(_checkCommandExists "dnf") == 0 ]]; then
    sudo dnf upgrade
else
    echo ":: ERROR - Platform not supported"
    echo "Press [ENTER] to close."
    read
fi
echo

# Flatpak
echo ":: Searching for Flatpak updates..."
flatpak update
echo

# Reload Waybar
pkill -RTMIN+1 waybar

# Finishing
echo ":: Update complete! Press [ENTER] to close."
read
