[Control Panel\Colors]

Background={{colors.surface.default.red}} {{colors.surface.default.green}} {{colors.surface.default.blue}}

ButtonFace={{colors.surface_container.default.red}} {{colors.surface_container.default.green}} {{colors.surface_container.default.blue}}
ButtonText={{colors.on_surface.default.red}} {{colors.on_surface.default.green}} {{colors.on_surface.default.blue}}

Window={{colors.surface_container_high.default.red}} {{colors.surface_container_high.default.green}} {{colors.surface_container_high.default.blue}}
WindowText={{colors.on_surface.default.red}} {{colors.on_surface.default.green}} {{colors.on_surface.default.blue}}

Hilight={{colors.primary.default.red}} {{colors.primary.default.green}} {{colors.primary.default.blue}}
HilightText={{colors.on_primary.default.red}} {{colors.on_primary.default.green}} {{colors.on_primary.default.blue}}

ButtonShadow={{colors.surface_variant.default.red}} {{colors.surface_variant.default.green}} {{colors.surface_variant.default.blue}}
ButtonDkShadow={{colors.outline.default.red}} {{colors.outline.default.green}} {{colors.outline.default.blue}}
ButtonLight={{colors.surface_bright.default.red}} {{colors.surface_bright.default.green}} {{colors.surface_bright.default.blue}}
ButtonHilight={{colors.surface_bright.default.red}} {{colors.surface_bright.default.green}} {{colors.surface_bright.default.blue}}

WindowFrame={{colors.outline.default.red}} {{colors.outline.default.green}} {{colors.outline.default.blue}}

ActiveTitle={{colors.primary.default.red}} {{colors.primary.default.green}} {{colors.primary.default.blue}}
InactiveTitle={{colors.surface_container.default.red}} {{colors.surface_container.default.green}} {{colors.surface_container.default.blue}}

TitleText={{colors.on_primary.default.red}} {{colors.on_primary.default.green}} {{colors.on_primary.default.blue}}
InactiveTitleText={{colors.on_surface.default.red}} {{colors.on_surface.default.green}} {{colors.on_surface.default.blue}}

Scrollbar={{colors.surface_container.default.red}} {{colors.surface_container.default.green}} {{colors.surface_container.default.blue}}
Menu={{colors.surface.default.red}} {{colors.surface.default.green}} {{colors.surface.default.blue}}
MenuText={{colors.on_surface.default.red}} {{colors.on_surface.default.green}} {{colors.on_surface.default.blue}}