[colors.primary]
background = "#f7f9ff"
foreground = "#181c20"
dim_foreground = "#7f849c"
bright_foreground = "#EEFCFE"

[colors.cursor]
text = "#42474d"
cursor = "#181c20"

[colors.vi_mode_cursor]
text = '#f7f9ff'
cursor = '#2a638b' 

[colors.search.matches]
foreground = '#dee3ea' 
background = '#66587b' 

[colors.search.focused_match]
foreground = '#dee3ea' 
background = '#2a638b' 
 
[colors.footer_bar]
foreground = '#dee3ea' 
background = '#2d3135' 

[colors.hints.start]
foreground = '#dee3ea' 
background = '#50606f' 

[colors.hints.end]
foreground = '#dee3ea' 
background = '#50606f' 

[colors.selection]
text = '#f7f9ff'
background = '#2a638b'

[colors.normal]
black = "#45475a"
#red = "#D60150"
#green = "#3BCA37"
#yellow = "#FFE700"
#blue = "#0065B5"
#magenta = "#F289B7"
#cyan = "#2CA19A"
red = '#ba1a1a' 
green = '#2a638b' 
yellow = '#98ccf9' 
blue = '#2a638b' 
magenta = '#66587b' 
cyan = '#50606f' 
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#D60150"
green = "#3BCA37"
yellow = "#FFE700"
blue = "#0065B5"
magenta = "#F289B7"
cyan = "#2CA19A"
white = "#a6adc8"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#FFE700"