-- Generated by nwg-displays on 2026-06-24 at 17:24:15. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@170.0",
    position = "2560x169",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@99.95",
    position = "0x169",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@100.0",
    position = "5120x0",
    scale = 1.0
})
