-- Generated by nwg-displays on 2026-06-04 at 11:55:05. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "2560x1440@143.86",
    position = "2560x169",
    scale = 1.0
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1440@59.95",
    position = "0x169",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "1920x1080@60.0",
    position = "5120x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-3",
    mode = "1920x1080@60.0",
    position = "5120x1080",
    scale = 1.0
})
