-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#101417',
  base01 = '#0b0f12',
  base02 = '#181c20',
  base03 = '#42474d',
  base04 = '#c2c7ce',
  base05 = '#e0e3e8',
  base06 = '#2d3135',
  base07 = '#363a3e',

  base08 = '#ffb4ab',
  base09 = '#d1bfe7',
  base0A = '#b8c8d9',
  base0B = '#98ccf9',
  base0C = '#4e4162',
  base0D = '#034b71',
  base0E = '#394856',
  base0F = '#93000a',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#034b71',
  fg = '#101417',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#ecdcff',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#d1bfe7',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#b8c8d9',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#2a638b',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#0b0f12',
  fg = '#98ccf9',
})