-- Auto-generated by Matugen

require('base16-colorscheme').setup({
  base00 = '#f7f9ff',
  base01 = '#ffffff',
  base02 = '#f1f4f9',
  base03 = '#c2c7ce',
  base04 = '#42474d',
  base05 = '#181c20',
  base06 = '#eef1f6',
  base07 = '#f7f9ff',

  base08 = '#ba1a1a',
  base09 = '#66587b',
  base0A = '#50606f',
  base0B = '#2a638b',
  base0C = '#ecdcff',
  base0D = '#cce5ff',
  base0E = '#d4e4f6',
  base0F = '#ffdad6',
})


-- We first theme base16, but we also need to fix some other colors that don't
-- contrast well by default

-- Helper function to set multiple highlight groups at once
local function set_hl_mutliple(groups, value)
  for _, v in pairs(groups) do
    vim.api.nvim_set_hl(0, v, value)
  end
end

-- Make selected text stand out more
vim.api.nvim_set_hl(0, 'Visual', {
  bg = '#cce5ff',
  fg = '#f7f9ff',
})

set_hl_mutliple({ 'TSComment', 'Comment' }, {
  fg = '#211534',
})

set_hl_mutliple({ 'TSMethod', 'Method' }, {
  fg = '#66587b',
})

set_hl_mutliple({ 'TSFunction', 'Function' }, {
  fg = '#50606f',
})

vim.api.nvim_set_hl(0, 'Keyword', {
  fg = '#98ccf9',
})

vim.api.nvim_set_hl(0, 'MsgArea', {
  bg = '#ffffff',
  fg = '#2a638b',
})