# Add your additional Hyprland configurations here
#env = TERMINAL,ghostty
#env = TERM,ghostty

exec-once = sleep 5 && otd-daemon
exec-once = sleep 3 && hyprpm reload -n
exec-once = sleep 4 && ~/.config/bongocat/launch.sh

exec-once = sleep 5 && ~/.config/hypr/scripts/power-daemon.sh
exec-once = sleep 10 && ~/.config/hypr/scripts/smart-monitor-power.sh