# Add your additional Hyprland configurations here
#env = TERMINAL,ghostty
#env = TERM,ghostty

exec-once = sleep 5 && otd-daemon
exec-once = sleep 3 && hyprpm reload -n
exec-once = sleep 4 && ~/.config/bongocat/launch.sh
